package test.analizadores;
import Errores.Error_;
import dataforge.Editor;
import java_cup.runtime.*;
import java.util.ArrayList;


parser code 
{:
    public static StringBuilder STR = new StringBuilder();
    public ArrayList <String> elementosParaImprimir = new ArrayList <String>();
    public ArrayList <Object> elemX = new ArrayList<>();
    public ArrayList <Object> elemY = new ArrayList<>();
    public static ArrayList<Object> elementos_arreglo = new ArrayList<>();






    public void syntax_error(Symbol s){
        //System.out.println("Error sintáctico: "+s.value+" linea: "+s.left+" columna: "+s.right);
        Error_ miError = new Error_(s.left,s.right,s.value.toString(),false);
        Editor.lista_errores.add(miError);
}
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
       System.out.println("Error sintáctico unrecovered: "+s.value+" linea: "+s.left+" columna: "+s.right);   
}


:} 

terminal String LLAVEIZ, LLAVEDE, OPERA, CONJ, EVALUAR, DOSPUNTOS, IGUALDAD, DIFERENCIA, UNION, INTERSECCION, COMPLEMENTO;
terminal String PARENTESISIZ, PARENTESISDE, COMA, PUNTOCOMA, CARACTERES, CARACTERUNICO, HASTA;

non terminal inicializarPrograma, codigo, comandos, crearConj, listaCaracteres, evaluarConj, operarConj;
non terminal listaOperaciones, listaConjuntos, operaciones;

inicializarPrograma ::= LLAVEIZ codigo LLAVEDE;

codigo ::= comandos
        | codigo comandos;

comandos ::= crearConj
        |    operarConj
        |    evaluarConj
;

crearConj ::= CONJ DOSPUNTOS CARACTERES:name IGUALDAD listaCaracteres:lista PUNTOCOMA;

operarConj ::= OPERA DOSPUNTOS CARACTERES:nameVarOpera IGUALDAD listaOperaciones listaConjuntos PUNTOCOMA;

evaluarConj ::= EVALUAR PARENTESISIZ LLAVEIZ listaCaracteres:lista LLAVEDE COMA CARACTERES:name PARENTESISDE PUNTOCOMA;

listaConjuntos ::= listaConjuntos LLAVEIZ CARACTERES:nameVarConj LLAVEDE
                | LLAVEIZ CARACTERES:nameVarConj LLAVEDE;

listaCaracteres ::= listaCaracteres COMA CARACTERUNICO
                | CARACTERUNICO 
                | CARACTERUNICO HASTA CARACTERUNICO;

listaOperaciones ::= listaOperaciones operaciones 
                | operaciones;

operaciones ::= DIFERENCIA
            | UNION
            | INTERSECCION
            | COMPLEMENTO;
