
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package test.analizadores;

import Errores.Error_;
import dataforge.Editor;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\047\000\002\005\005\000\002\002\004\000\002\006" +
    "\003\000\002\006\004\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\007\003\000\002" +
    "\002\014\000\002\002\014\000\002\003\003\000\002\003" +
    "\003\000\002\004\003\000\002\004\003\000\002\010\017" +
    "\000\002\010\017\000\002\011\005\000\002\011\003\000" +
    "\002\012\005\000\002\012\003\000\002\014\021\000\002" +
    "\014\021\000\002\014\021\000\002\014\021\000\002\014" +
    "\021\000\002\015\021\000\002\015\021\000\002\015\021" +
    "\000\002\015\021\000\002\015\021\000\002\015\021\000" +
    "\002\016\012\000\002\017\047\000\002\020\067\000\002" +
    "\013\035" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0119\000\004\056\005\001\002\000\004\002\u011b\001" +
    "\002\000\016\006\015\011\007\033\012\034\010\044\017" +
    "\060\024\001\002\000\020\006\ufff8\011\ufff8\033\ufff8\034" +
    "\ufff8\044\ufff8\057\ufff8\060\ufff8\001\002\000\004\051\u0104" +
    "\001\002\000\004\030\352\001\002\000\020\006\ufff9\011" +
    "\ufff9\033\ufff9\034\ufff9\044\ufff9\057\ufff9\060\ufff9\001\002" +
    "\000\004\030\266\001\002\000\020\006\ufff7\011\ufff7\033" +
    "\ufff7\034\ufff7\044\ufff7\057\ufff7\060\ufff7\001\002\000\020" +
    "\006\ufffd\011\ufffd\033\ufffd\034\ufffd\044\ufffd\057\ufffd\060" +
    "\ufffd\001\002\000\004\051\115\001\002\000\020\006\ufffb" +
    "\011\ufffb\033\ufffb\034\ufffb\044\ufffb\057\ufffb\060\ufffb\001" +
    "\002\000\004\051\106\001\002\000\020\006\ufffc\011\ufffc" +
    "\033\ufffc\034\ufffc\044\ufffc\057\ufffc\060\ufffc\001\002\000" +
    "\020\006\uffff\011\uffff\033\uffff\034\uffff\044\uffff\057\uffff" +
    "\060\uffff\001\002\000\020\006\015\011\007\033\012\034" +
    "\010\044\017\057\105\060\024\001\002\000\020\006\ufffa" +
    "\011\ufffa\033\ufffa\034\ufffa\044\ufffa\057\ufffa\060\ufffa\001" +
    "\002\000\004\030\026\001\002\000\020\006\ufff6\011\ufff6" +
    "\033\ufff6\034\ufff6\044\ufff6\057\ufff6\060\ufff6\001\002\000" +
    "\004\061\027\001\002\000\004\051\030\001\002\000\004" +
    "\051\031\001\002\000\004\004\032\001\002\000\004\047" +
    "\033\001\002\000\004\013\034\001\002\000\006\054\040" +
    "\055\036\001\002\000\010\007\uffea\022\uffea\032\uffea\001" +
    "\002\000\010\007\ufff0\022\ufff0\032\ufff0\001\002\000\006" +
    "\022\042\032\041\001\002\000\010\007\ufff1\022\ufff1\032" +
    "\ufff1\001\002\000\006\054\040\055\036\001\002\000\004" +
    "\007\043\001\002\000\004\050\044\001\002\000\004\062" +
    "\045\001\002\000\004\051\046\001\002\000\004\051\047" +
    "\001\002\000\004\005\050\001\002\000\004\047\051\001" +
    "\002\000\004\013\052\001\002\000\006\053\055\054\056" +
    "\001\002\000\006\022\060\032\057\001\002\000\006\022" +
    "\uffec\032\uffec\001\002\000\012\007\ufff3\022\ufff3\031\ufff3" +
    "\032\ufff3\001\002\000\012\007\ufff2\022\ufff2\031\ufff2\032" +
    "\ufff2\001\002\000\006\053\055\054\056\001\002\000\004" +
    "\007\061\001\002\000\004\050\062\001\002\000\004\063" +
    "\063\001\002\000\004\051\064\001\002\000\004\051\065" +
    "\001\002\000\004\004\066\001\002\000\004\047\067\001" +
    "\002\000\004\055\070\001\002\000\004\007\071\001\002" +
    "\000\004\050\072\001\002\000\004\064\073\001\002\000" +
    "\004\060\074\001\002\000\004\007\075\001\002\000\004" +
    "\050\076\001\002\000\004\031\077\001\002\000\004\007" +
    "\100\001\002\000\004\050\101\001\002\000\020\006\uffdd" +
    "\011\uffdd\033\uffdd\034\uffdd\044\uffdd\057\uffdd\060\uffdd\001" +
    "\002\000\006\022\uffed\032\uffed\001\002\000\010\007\uffeb" +
    "\022\uffeb\032\uffeb\001\002\000\020\006\ufffe\011\ufffe\033" +
    "\ufffe\034\ufffe\044\ufffe\057\ufffe\060\ufffe\001\002\000\004" +
    "\002\001\001\002\000\004\051\107\001\002\000\004\045" +
    "\110\001\002\000\004\047\111\001\002\000\006\054\040" +
    "\055\036\001\002\000\006\007\113\032\041\001\002\000" +
    "\004\050\114\001\002\000\020\006\uffde\011\uffde\033\uffde" +
    "\034\uffde\044\uffde\057\uffde\060\uffde\001\002\000\006\004" +
    "\117\005\116\001\002\000\004\051\127\001\002\000\004" +
    "\051\120\001\002\000\004\051\121\001\002\000\004\054" +
    "\122\001\002\000\004\010\123\001\002\000\006\054\040" +
    "\055\036\001\002\000\004\007\125\001\002\000\004\050" +
    "\126\001\002\000\020\006\ufff4\011\ufff4\033\ufff4\034\ufff4" +
    "\044\ufff4\057\ufff4\060\ufff4\001\002\000\004\051\130\001" +
    "\002\000\004\054\131\001\002\000\004\010\132\001\002" +
    "\000\034\023\134\024\135\025\143\026\142\027\136\036" +
    "\144\037\133\040\141\041\140\042\137\043\146\053\055" +
    "\054\056\001\002\000\004\030\257\001\002\000\004\030" +
    "\250\001\002\000\004\030\241\001\002\000\004\030\232" +
    "\001\002\000\004\030\223\001\002\000\004\030\214\001" +
    "\002\000\004\030\205\001\002\000\004\030\176\001\002" +
    "\000\004\030\167\001\002\000\004\030\160\001\002\000" +
    "\004\007\156\001\002\000\004\030\147\001\002\000\004" +
    "\013\150\001\002\000\006\053\055\054\056\001\002\000" +
    "\006\022\152\032\057\001\002\000\004\031\153\001\002" +
    "\000\004\007\154\001\002\000\004\050\155\001\002\000" +
    "\020\006\uffdf\011\uffdf\033\uffdf\034\uffdf\044\uffdf\057\uffdf" +
    "\060\uffdf\001\002\000\004\050\157\001\002\000\020\006" +
    "\ufff5\011\ufff5\033\ufff5\034\ufff5\044\ufff5\057\ufff5\060\ufff5" +
    "\001\002\000\004\013\161\001\002\000\006\053\055\054" +
    "\056\001\002\000\006\022\163\032\057\001\002\000\004" +
    "\031\164\001\002\000\004\007\165\001\002\000\004\050" +
    "\166\001\002\000\020\006\uffe4\011\uffe4\033\uffe4\034\uffe4" +
    "\044\uffe4\057\uffe4\060\uffe4\001\002\000\006\053\055\054" +
    "\056\001\002\000\004\032\171\001\002\000\006\053\055" +
    "\054\056\001\002\000\004\031\173\001\002\000\004\007" +
    "\174\001\002\000\004\050\175\001\002\000\020\006\uffe7" +
    "\011\uffe7\033\uffe7\034\uffe7\044\uffe7\057\uffe7\060\uffe7\001" +
    "\002\000\006\053\055\054\056\001\002\000\004\032\200" +
    "\001\002\000\006\053\055\054\056\001\002\000\004\031" +
    "\202\001\002\000\004\007\203\001\002\000\004\050\204" +
    "\001\002\000\020\006\uffe6\011\uffe6\033\uffe6\034\uffe6\044" +
    "\uffe6\057\uffe6\060\uffe6\001\002\000\004\013\206\001\002" +
    "\000\006\053\055\054\056\001\002\000\006\022\210\032" +
    "\057\001\002\000\004\031\211\001\002\000\004\007\212" +
    "\001\002\000\004\050\213\001\002\000\020\006\uffe2\011" +
    "\uffe2\033\uffe2\034\uffe2\044\uffe2\057\uffe2\060\uffe2\001\002" +
    "\000\004\013\215\001\002\000\006\053\055\054\056\001" +
    "\002\000\006\022\217\032\057\001\002\000\004\031\220" +
    "\001\002\000\004\007\221\001\002\000\004\050\222\001" +
    "\002\000\020\006\uffe1\011\uffe1\033\uffe1\034\uffe1\044\uffe1" +
    "\057\uffe1\060\uffe1\001\002\000\004\013\224\001\002\000" +
    "\006\053\055\054\056\001\002\000\006\022\226\032\057" +
    "\001\002\000\004\031\227\001\002\000\004\007\230\001" +
    "\002\000\004\050\231\001\002\000\020\006\uffe0\011\uffe0" +
    "\033\uffe0\034\uffe0\044\uffe0\057\uffe0\060\uffe0\001\002\000" +
    "\006\053\055\054\056\001\002\000\004\032\234\001\002" +
    "\000\006\053\055\054\056\001\002\000\004\031\236\001" +
    "\002\000\004\007\237\001\002\000\004\050\240\001\002" +
    "\000\020\006\uffe5\011\uffe5\033\uffe5\034\uffe5\044\uffe5\057" +
    "\uffe5\060\uffe5\001\002\000\006\053\055\054\056\001\002" +
    "\000\004\032\243\001\002\000\006\053\055\054\056\001" +
    "\002\000\004\031\245\001\002\000\004\007\246\001\002" +
    "\000\004\050\247\001\002\000\020\006\uffe8\011\uffe8\033" +
    "\uffe8\034\uffe8\044\uffe8\057\uffe8\060\uffe8\001\002\000\006" +
    "\053\055\054\056\001\002\000\004\032\252\001\002\000" +
    "\006\053\055\054\056\001\002\000\004\031\254\001\002" +
    "\000\004\007\255\001\002\000\004\050\256\001\002\000" +
    "\020\006\uffe9\011\uffe9\033\uffe9\034\uffe9\044\uffe9\057\uffe9" +
    "\060\uffe9\001\002\000\004\013\260\001\002\000\006\053" +
    "\055\054\056\001\002\000\006\022\262\032\057\001\002" +
    "\000\004\031\263\001\002\000\004\007\264\001\002\000" +
    "\004\050\265\001\002\000\020\006\uffe3\011\uffe3\033\uffe3" +
    "\034\uffe3\044\uffe3\057\uffe3\060\uffe3\001\002\000\004\063" +
    "\267\001\002\000\004\051\270\001\002\000\004\051\271" +
    "\001\002\000\004\004\272\001\002\000\004\047\273\001" +
    "\002\000\004\055\274\001\002\000\004\007\275\001\002" +
    "\000\004\050\276\001\002\000\004\014\277\001\002\000" +
    "\004\051\300\001\002\000\004\051\301\001\002\000\004" +
    "\004\302\001\002\000\004\047\303\001\002\000\004\013" +
    "\304\001\002\000\006\054\040\055\036\001\002\000\006" +
    "\022\306\032\041\001\002\000\004\007\307\001\002\000" +
    "\004\050\310\001\002\000\004\015\311\001\002\000\004" +
    "\051\312\001\002\000\004\051\313\001\002\000\004\005" +
    "\314\001\002\000\004\047\315\001\002\000\004\013\316" +
    "\001\002\000\006\053\055\054\056\001\002\000\006\022" +
    "\320\032\057\001\002\000\004\007\321\001\002\000\004" +
    "\050\322\001\002\000\004\016\323\001\002\000\004\051" +
    "\324\001\002\000\004\051\325\001\002\000\004\004\326" +
    "\001\002\000\004\047\327\001\002\000\004\055\330\001" +
    "\002\000\004\007\331\001\002\000\004\050\332\001\002" +
    "\000\004\017\333\001\002\000\004\051\334\001\002\000" +
    "\004\051\335\001\002\000\004\004\336\001\002\000\004" +
    "\047\337\001\002\000\004\055\340\001\002\000\004\007" +
    "\341\001\002\000\004\050\342\001\002\000\004\064\343" +
    "\001\002\000\004\033\344\001\002\000\004\007\345\001" +
    "\002\000\004\050\346\001\002\000\004\031\347\001\002" +
    "\000\004\007\350\001\002\000\004\050\351\001\002\000" +
    "\020\006\uffdc\011\uffdc\033\uffdc\034\uffdc\044\uffdc\057\uffdc" +
    "\060\uffdc\001\002\000\004\063\353\001\002\000\004\051" +
    "\354\001\002\000\004\051\355\001\002\000\004\004\356" +
    "\001\002\000\004\047\357\001\002\000\004\055\360\001" +
    "\002\000\004\007\361\001\002\000\004\050\362\001\002" +
    "\000\004\062\363\001\002\000\004\051\364\001\002\000" +
    "\004\051\365\001\002\000\004\004\366\001\002\000\004" +
    "\047\367\001\002\000\004\013\370\001\002\000\006\054" +
    "\040\055\036\001\002\000\006\022\372\032\041\001\002" +
    "\000\004\007\373\001\002\000\004\050\374\001\002\000" +
    "\004\064\375\001\002\000\004\034\376\001\002\000\004" +
    "\007\377\001\002\000\004\050\u0100\001\002\000\004\031" +
    "\u0101\001\002\000\004\007\u0102\001\002\000\004\050\u0103" +
    "\001\002\000\020\006\uffdb\011\uffdb\033\uffdb\034\uffdb\044" +
    "\uffdb\057\uffdb\060\uffdb\001\002\000\006\004\u0106\005\u0105" +
    "\001\002\000\004\051\u0111\001\002\000\004\051\u0107\001" +
    "\002\000\004\051\u0108\001\002\000\004\012\u0109\001\002" +
    "\000\004\054\u010a\001\002\000\004\010\u010b\001\002\000" +
    "\004\013\u010c\001\002\000\006\054\040\055\036\001\002" +
    "\000\006\022\u010e\032\041\001\002\000\004\007\u010f\001" +
    "\002\000\004\050\u0110\001\002\000\020\006\uffee\011\uffee" +
    "\033\uffee\034\uffee\044\uffee\057\uffee\060\uffee\001\002\000" +
    "\004\051\u0112\001\002\000\004\012\u0113\001\002\000\004" +
    "\054\u0114\001\002\000\004\010\u0115\001\002\000\004\013" +
    "\u0116\001\002\000\006\053\055\054\056\001\002\000\006" +
    "\022\u0118\032\057\001\002\000\004\007\u0119\001\002\000" +
    "\004\050\u011a\001\002\000\020\006\uffef\011\uffef\033\uffef" +
    "\034\uffef\044\uffef\057\uffef\060\uffef\001\002\000\004\002" +
    "\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0119\000\004\005\003\001\001\000\002\001\001\000" +
    "\026\002\013\006\021\007\020\010\017\013\012\014\015" +
    "\015\022\016\010\017\005\020\024\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\024\002\013\007\103\010" +
    "\017\013\012\014\015\015\022\016\010\017\005\020\024" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\004\034\012\036\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\102\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\003\053" +
    "\011\052\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\101\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\004\034" +
    "\012\111\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\004\123\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\144\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\003\053\011\150\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\003\053\011\161\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\003\167\001\001\000\002\001\001\000\004" +
    "\003\171\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\176\001\001" +
    "\000\002\001\001\000\004\003\200\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\003\053\011\206\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\003" +
    "\053\011\215\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\003\053\011\224\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\232\001\001\000\002" +
    "\001\001\000\004\003\234\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\003\241\001\001\000\002\001\001\000\004\003\243\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\250\001\001\000\002\001" +
    "\001\000\004\003\252\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\003\053\011\260\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\004\034\012\304" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\003\053\011\316\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\004\034\012\370\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\004\034\012" +
    "\u010c\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\053\011\u0116\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s){
        //System.out.println("Error sintáctico: "+s.value+" linea: "+s.left+" columna: "+s.right);
        Error_ miError = new Error_(s.left,s.right,s.value.toString(),false);
        Editor.lista_errores.add(miError);
}
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
       // System.out.println("Error sintáctico unrecovered: "+s.value+" linea: "+s.left+" columna: "+s.right);
        Error_ miError = new Error_(s.left,s.right,s.value.toString(),false);
        Editor.lista_errores.add(miError);    
}




/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // inicializarPrograma ::= PROGRAM codigo ENDPROGRAM 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicializarPrograma",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= inicializarPrograma EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // codigo ::= comandos 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("codigo",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // codigo ::= codigo comandos 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("codigo",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // comandos ::= declararVariable 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comandos",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // comandos ::= declararArreglos 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comandos",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // comandos ::= declararAritmetica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comandos",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // comandos ::= declararEstadisticas 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comandos",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // comandos ::= declararPrint 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comandos",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // comandos ::= declararGraficaPie 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comandos",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // comandos ::= declararGraficaHistograma 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comandos",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // comandos ::= declararGraficaLine 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comandos",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declararVariable ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD declararDouble END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararVariable",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declararVariable ::= VAR DOSPUNTOS CHAR DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD declararChar END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararVariable",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // declararDouble ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararDouble",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declararDouble ::= CARACTERES 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararDouble",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declararChar ::= CARACTERES 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararChar",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // declararChar ::= CHARCOMILLAS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararChar",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declararArreglos ::= ARR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS ARROBA CARACTERES IGUALDAD CORCHETEIZ listaArreglosDouble CORCHETEDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararArreglos",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declararArreglos ::= ARR DOSPUNTOS CHAR DOSPUNTOS DOSPUNTOS ARROBA CARACTERES IGUALDAD CORCHETEIZ listaArreglosChar CORCHETEDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararArreglos",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // listaArreglosDouble ::= listaArreglosDouble COMA declararDouble 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaArreglosDouble",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // listaArreglosDouble ::= declararDouble 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaArreglosDouble",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // listaArreglosChar ::= listaArreglosChar COMA declararChar 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaArreglosChar",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // listaArreglosChar ::= declararChar 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaArreglosChar",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // declararAritmetica ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD SUM PARENTESISIZ declararDouble COMA declararDouble PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararAritmetica",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // declararAritmetica ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD RES PARENTESISIZ declararDouble COMA declararDouble PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararAritmetica",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // declararAritmetica ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD MUL PARENTESISIZ declararDouble COMA declararDouble PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararAritmetica",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // declararAritmetica ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD DIV PARENTESISIZ declararDouble COMA declararDouble PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararAritmetica",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declararAritmetica ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD MOD PARENTESISIZ declararDouble COMA declararDouble PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararAritmetica",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // declararEstadisticas ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD MEDIA PARENTESISIZ CORCHETEIZ listaArreglosDouble CORCHETEDE PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararEstadisticas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // declararEstadisticas ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD MEDIANA PARENTESISIZ CORCHETEIZ listaArreglosDouble CORCHETEDE PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararEstadisticas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // declararEstadisticas ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD MODA PARENTESISIZ CORCHETEIZ listaArreglosDouble CORCHETEDE PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararEstadisticas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // declararEstadisticas ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD VARIANZA PARENTESISIZ CORCHETEIZ listaArreglosDouble CORCHETEDE PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararEstadisticas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // declararEstadisticas ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD MAX PARENTESISIZ CORCHETEIZ listaArreglosDouble CORCHETEDE PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararEstadisticas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // declararEstadisticas ::= VAR DOSPUNTOS DOUBLE DOSPUNTOS DOSPUNTOS CARACTERES IGUALDAD MIN PARENTESISIZ CORCHETEIZ listaArreglosDouble CORCHETEDE PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararEstadisticas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // declararPrint ::= CONSOLE DOSPUNTOS DOSPUNTOS PRINT IGUAL listaArreglosChar END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararPrint",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // declararGraficaPie ::= GRAPHPIE PARENTESISIZ LABEL DOSPUNTOS DOSPUNTOS CHAR IGUAL CORCHETEIZ listaArreglosChar CORCHETEDE END PUNTOCOMA VALUES DOSPUNTOS DOSPUNTOS DOUBLE IGUAL CORCHETEIZ listaArreglosDouble CORCHETEDE END PUNTOCOMA TITULO DOSPUNTOS DOSPUNTOS CHAR IGUAL CHARCOMILLAS END PUNTOCOMA EXEC GRAPHPIE END PUNTOCOMA PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararGraficaPie",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-36)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // declararGraficaLine ::= GRAPHLINE PARENTESISIZ TITULO DOSPUNTOS DOSPUNTOS CHAR IGUAL CHARCOMILLAS END PUNTOCOMA EJEX DOSPUNTOS DOSPUNTOS CHAR IGUAL CORCHETEIZ listaArreglosChar CORCHETEDE END PUNTOCOMA EJEY DOSPUNTOS DOSPUNTOS DOUBLE IGUAL CORCHETEIZ listaArreglosDouble CORCHETEDE END PUNTOCOMA TITULOX DOSPUNTOS DOSPUNTOS CHAR IGUAL CHARCOMILLAS END PUNTOCOMA TITULOY DOSPUNTOS DOSPUNTOS CHAR IGUAL CHARCOMILLAS END PUNTOCOMA EXEC GRAPHLINE END PUNTOCOMA PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararGraficaLine",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-52)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // declararGraficaHistograma ::= HISTOGRAMA PARENTESISIZ TITULO DOSPUNTOS DOSPUNTOS CHAR IGUAL CHARCOMILLAS END PUNTOCOMA VALUES DOSPUNTOS DOSPUNTOS CHAR IGUAL CORCHETEIZ listaArreglosChar CORCHETEDE END PUNTOCOMA EXEC HISTOGRAMA END PUNTOCOMA PARENTESISDE END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declararGraficaHistograma",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-26)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
