// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/test/Analizadores/lex.jflex


package test.analizadores;
import java_cup.runtime.Symbol;
import Errores.Error_;
import static dataforge.Editor.lista_errores;


@SuppressWarnings("fallthrough")
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\2\2\1\1\22\0\1\3\1\0\1\4"+
    "\5\0\1\5\1\6\2\0\1\7\1\10\1\11\1\0"+
    "\12\12\1\13\1\14\1\15\1\16\2\0\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\25\1\32\1\33\1\34\1\35\1\36\1\25"+
    "\1\37\1\40\1\41\1\42\1\43\1\25\1\44\1\45"+
    "\1\46\1\47\1\0\1\50\1\0\1\25\1\0\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\25\1\32\1\33\1\34\1\35\1\36\1\25"+
    "\1\37\1\40\1\41\1\42\1\43\1\25\1\44\1\45"+
    "\1\46\12\0\1\2\252\0\2\51\115\0\1\52\u01a8\0"+
    "\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\12\16\13\1\14\1\15"+
    "\1\1\2\0\1\16\5\13\1\0\5\13\1\0\6\13"+
    "\1\0\4\13\1\0\1\13\1\0\1\17\1\6\1\20"+
    "\3\13\1\21\1\13\1\21\1\13\1\22\3\13\1\0"+
    "\1\13\1\23\1\13\1\24\1\25\1\26\1\24\2\13"+
    "\1\0\2\27\1\30\1\13\1\0\1\13\1\31\1\30"+
    "\3\13\1\0\1\13\1\32\1\33\1\0\1\34\2\13"+
    "\1\0\2\13\1\0\1\35\2\13\1\0\1\13\1\0"+
    "\2\13\2\0\2\13\1\0\1\13\1\0\2\13\1\0"+
    "\1\36\2\37\1\40\1\13\1\40\1\13\1\0\2\13"+
    "\1\0\1\41\1\42\1\13\1\0\1\43\1\0\3\13"+
    "\1\0\1\13\1\0\1\13\2\44\2\45\1\13\1\0"+
    "\2\46\1\0\1\13\1\0\1\13\1\0\1\13\1\0"+
    "\2\47\1\50\1\51\1\52\1\51\1\52\1\13\2\0"+
    "\1\13\1\0\2\53\1\13\1\0\2\54\1\0\2\55"+
    "\1\13\2\0\2\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[191];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\53\0\53\0\53\0\254"+
    "\0\53\0\53\0\327\0\53\0\53\0\u0102\0\u012d\0\u0158"+
    "\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285\0\u02b0"+
    "\0\u02db\0\u0306\0\u0331\0\53\0\53\0\u035c\0\u0387\0\u03b2"+
    "\0\53\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4\0\u04df"+
    "\0\u050a\0\u0535\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637"+
    "\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f"+
    "\0\u07ba\0\u07e5\0\u0810\0\53\0\u03b2\0\u012d\0\u083b\0\u0866"+
    "\0\u0891\0\u012d\0\u08bc\0\53\0\u08e7\0\u0912\0\u093d\0\u0968"+
    "\0\u0993\0\u09be\0\u09e9\0\u012d\0\u0a14\0\u012d\0\u0a3f\0\u012d"+
    "\0\53\0\u0a6a\0\u0a95\0\u0ac0\0\u012d\0\53\0\u012d\0\u0aeb"+
    "\0\u0b16\0\u0b41\0\u0b6c\0\53\0\u0b97\0\u0bc2\0\u0bed\0\u0c18"+
    "\0\u0c43\0\u012d\0\u012d\0\u0c6e\0\u012d\0\u0c99\0\u0cc4\0\u0cef"+
    "\0\u0d1a\0\u0d45\0\u0d70\0\u012d\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c"+
    "\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74"+
    "\0\u0f9f\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\u012d\0\u1076\0\u10a1"+
    "\0\u012d\0\u10cc\0\53\0\u10f7\0\u1122\0\u114d\0\u1178\0\u11a3"+
    "\0\53\0\u012d\0\u11ce\0\u11f9\0\u012d\0\u1224\0\u124f\0\u127a"+
    "\0\u12a5\0\u12d0\0\u12fb\0\u1326\0\u1351\0\u137c\0\u13a7\0\u012d"+
    "\0\53\0\u13d2\0\u13fd\0\u012d\0\53\0\u1428\0\u1453\0\u147e"+
    "\0\u14a9\0\u14d4\0\u14ff\0\u152a\0\u012d\0\53\0\u012d\0\u012d"+
    "\0\u012d\0\53\0\53\0\u1555\0\u1580\0\u15ab\0\u15d6\0\u1601"+
    "\0\u012d\0\53\0\u162c\0\u1657\0\u012d\0\53\0\u1682\0\u012d"+
    "\0\53\0\u16ad\0\u16d8\0\u1703\0\u012d\0\53\0\53";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[191];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\2\2\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\17\1\23\1\24\2\17"+
    "\1\25\1\26\2\17\1\27\1\30\1\31\1\32\1\17"+
    "\1\33\3\17\1\34\1\35\1\2\1\36\54\0\1\3"+
    "\1\0\1\3\52\0\1\37\6\0\1\37\5\0\27\37"+
    "\15\0\1\40\1\10\5\0\27\17\14\0\1\41\54\0"+
    "\1\17\5\0\17\17\1\42\7\17\16\0\1\17\5\0"+
    "\27\17\16\0\1\17\5\0\7\17\1\43\5\17\1\44"+
    "\11\17\16\0\1\17\5\0\10\17\1\45\4\17\1\46"+
    "\11\17\2\0\1\47\13\0\1\17\5\0\11\17\1\50"+
    "\2\17\1\51\7\17\1\52\2\17\16\0\1\17\5\0"+
    "\17\17\1\53\7\17\16\0\1\17\5\0\10\17\1\54"+
    "\16\17\2\0\1\55\13\0\1\17\5\0\1\56\26\17"+
    "\16\0\1\17\5\0\1\57\3\17\1\60\3\17\1\61"+
    "\4\17\1\62\4\17\1\63\4\17\2\0\1\64\13\0"+
    "\1\17\5\0\17\17\1\65\7\17\16\0\1\17\5\0"+
    "\4\17\1\66\22\17\16\0\1\17\5\0\22\17\1\67"+
    "\4\17\16\0\1\17\5\0\10\17\1\70\16\17\2\0"+
    "\1\71\13\0\1\17\5\0\1\72\26\17\46\0\1\73"+
    "\13\0\1\37\1\74\5\0\1\37\5\0\27\37\16\0"+
    "\1\75\52\0\1\17\5\0\17\17\1\76\7\17\16\0"+
    "\1\17\5\0\1\77\26\17\16\0\1\17\5\0\12\17"+
    "\1\100\1\17\1\101\12\17\16\0\1\17\5\0\23\17"+
    "\1\102\3\17\16\0\1\17\5\0\22\17\1\103\4\17"+
    "\47\0\1\104\21\0\1\17\5\0\4\17\1\105\22\17"+
    "\16\0\1\17\5\0\3\17\1\106\23\17\16\0\1\17"+
    "\5\0\4\17\1\107\22\17\16\0\1\17\5\0\1\110"+
    "\26\17\16\0\1\17\5\0\20\17\1\111\6\17\3\0"+
    "\1\112\40\0\1\112\11\0\1\112\12\0\1\17\5\0"+
    "\1\17\1\113\25\17\16\0\1\17\5\0\24\17\1\114"+
    "\2\17\16\0\1\17\5\0\3\17\1\115\23\17\16\0"+
    "\1\17\5\0\14\17\1\116\12\17\16\0\1\17\5\0"+
    "\3\17\1\117\23\17\16\0\1\17\5\0\12\17\1\120"+
    "\14\17\40\0\1\121\30\0\1\17\5\0\10\17\1\122"+
    "\4\17\1\123\11\17\2\0\1\124\13\0\1\17\5\0"+
    "\20\17\1\125\6\17\3\0\1\126\12\0\1\17\5\0"+
    "\13\17\1\127\13\17\16\0\1\17\5\0\21\17\1\130"+
    "\5\17\45\0\1\131\23\0\1\17\5\0\12\17\1\132"+
    "\4\17\1\133\7\17\37\0\1\134\31\0\1\17\5\0"+
    "\17\17\1\135\7\17\16\0\1\17\5\0\22\17\1\136"+
    "\4\17\16\0\1\17\5\0\20\17\1\137\6\17\3\0"+
    "\1\140\12\0\1\17\5\0\1\17\1\141\25\17\16\0"+
    "\1\17\5\0\24\17\1\142\1\143\1\17\7\0\1\144"+
    "\6\0\1\17\5\0\27\17\16\0\1\17\5\0\2\17"+
    "\1\145\24\17\16\0\1\17\5\0\16\17\1\146\10\17"+
    "\16\0\1\17\5\0\21\17\1\147\5\17\45\0\1\150"+
    "\23\0\1\17\5\0\4\17\1\151\22\17\16\0\1\17"+
    "\5\0\10\17\1\152\16\17\2\0\1\153\13\0\1\17"+
    "\5\0\1\154\26\17\16\0\1\17\5\0\14\17\1\155"+
    "\12\17\16\0\1\17\5\0\6\17\1\156\20\17\40\0"+
    "\1\157\30\0\1\17\5\0\22\17\1\160\4\17\46\0"+
    "\1\161\22\0\1\17\5\0\22\17\1\162\4\17\16\0"+
    "\1\17\5\0\10\17\1\163\16\17\2\0\1\164\13\0"+
    "\1\17\5\0\27\17\1\165\15\0\1\17\5\0\13\17"+
    "\1\166\13\17\16\0\1\17\5\0\15\17\1\167\11\17"+
    "\41\0\1\170\27\0\1\17\5\0\12\17\1\171\14\17"+
    "\42\0\1\172\26\0\1\17\5\0\7\17\1\173\17\17"+
    "\16\0\1\17\5\0\15\17\1\174\11\17\41\0\1\175"+
    "\27\0\1\17\5\0\12\17\1\176\14\17\16\0\1\17"+
    "\5\0\1\177\26\17\24\0\1\200\44\0\1\17\5\0"+
    "\21\17\1\201\5\17\16\0\1\17\5\0\17\17\1\202"+
    "\7\17\45\0\1\203\23\0\1\17\5\0\12\17\1\204"+
    "\14\17\36\0\1\205\32\0\1\17\5\0\4\17\1\206"+
    "\22\17\16\0\1\17\5\0\1\207\26\17\24\0\1\210"+
    "\102\0\1\211\14\0\1\17\5\0\14\17\1\212\12\17"+
    "\16\0\1\17\5\0\12\17\1\213\14\17\36\0\1\214"+
    "\32\0\1\17\5\0\4\17\1\215\22\17\43\0\1\216"+
    "\25\0\1\17\5\0\12\17\1\217\3\17\1\220\10\17"+
    "\16\0\1\17\5\0\6\17\1\221\20\17\32\0\1\222"+
    "\36\0\1\17\5\0\14\17\1\223\12\17\40\0\1\224"+
    "\30\0\1\17\5\0\1\225\26\17\16\0\1\17\5\0"+
    "\15\17\1\226\11\17\41\0\1\227\27\0\1\17\5\0"+
    "\20\17\1\230\6\17\3\0\1\231\12\0\1\17\5\0"+
    "\14\17\1\232\12\17\40\0\1\233\30\0\1\17\5\0"+
    "\4\17\1\234\22\17\30\0\1\235\63\0\1\236\27\0"+
    "\1\17\5\0\10\17\1\237\16\17\2\0\1\240\13\0"+
    "\1\17\5\0\10\17\1\241\16\17\2\0\1\242\13\0"+
    "\1\17\5\0\17\17\1\243\7\17\43\0\1\244\25\0"+
    "\1\17\5\0\1\245\26\17\24\0\1\246\44\0\1\17"+
    "\5\0\13\17\1\247\13\17\16\0\1\17\5\0\24\17"+
    "\1\250\1\251\1\17\50\0\1\252\1\253\17\0\1\17"+
    "\5\0\26\17\1\254\52\0\1\255\32\0\1\256\36\0"+
    "\1\17\5\0\14\17\1\257\12\17\40\0\1\260\30\0"+
    "\1\17\5\0\4\17\1\261\22\17\30\0\1\262\40\0"+
    "\1\17\5\0\1\263\26\17\24\0\1\264\44\0\1\17"+
    "\5\0\1\265\26\17\24\0\1\266\71\0\1\267\25\0"+
    "\1\17\5\0\4\17\1\270\22\17\30\0\1\271\40\0"+
    "\1\17\5\0\13\17\1\272\13\17\37\0\1\273\37\0"+
    "\1\274\44\0\1\17\5\0\1\275\26\17\24\0\1\276"+
    "\65\0\1\277\17\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5934];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\3\11\1\1\2\11\1\1\2\11"+
    "\16\1\2\11\1\1\2\0\1\11\5\1\1\0\5\1"+
    "\1\0\6\1\1\0\4\1\1\0\1\1\1\0\1\11"+
    "\7\1\1\11\5\1\1\0\6\1\1\11\2\1\1\0"+
    "\1\1\1\11\2\1\1\0\2\1\1\11\3\1\1\0"+
    "\3\1\1\0\3\1\1\0\2\1\1\0\3\1\1\0"+
    "\1\1\1\0\2\1\2\0\2\1\1\0\1\1\1\0"+
    "\2\1\1\0\5\1\1\11\1\1\1\0\2\1\1\0"+
    "\1\11\2\1\1\0\1\1\1\0\3\1\1\0\1\1"+
    "\1\0\4\1\1\11\1\1\1\0\1\1\1\11\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\11"+
    "\3\1\2\11\1\1\2\0\1\1\1\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\11\1\0\1\1\1\11\1\1"+
    "\2\0\1\1\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[191];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
      yyline = 1; 
    yycolumn=1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { //System.out.println("Lexical error: "+yytext()+" linea: "+yyline+" columna: "+yycolumn);
    Error_ nuevoError = new Error_(yyline,yycolumn,yytext(),true);
    lista_errores.add(nuevoError);
    //System.out.println(nuevoError.toString());
            }
          // fall through
          case 48: break;
          case 2:
            { 
            }
          // fall through
          case 49: break;
          case 3:
            { System.out.println("("); 
return new Symbol(sym.PARENTESISIZ,yyline,yycolumn, yytext());
            }
          // fall through
          case 50: break;
          case 4:
            { System.out.println(")"); 
return new Symbol(sym.PARENTESISDE,yyline,yycolumn, yytext());
            }
          // fall through
          case 51: break;
          case 5:
            { System.out.println(","); 
return new Symbol(sym.COMA,yyline,yycolumn, yytext());
            }
          // fall through
          case 52: break;
          case 6:
            { System.out.println("algun decimal o entero"); 
return new Symbol(sym.DECIMAL,yyline,yycolumn, yytext());
            }
          // fall through
          case 53: break;
          case 7:
            { System.out.println(":"); 
return new Symbol(sym.DOSPUNTOS,yyline,yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 8:
            { System.out.println(";"); 
return new Symbol(sym.PUNTOCOMA,yyline,yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 9:
            { System.out.println("="); 
return new Symbol(sym.IGUAL,yyline,yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 10:
            { System.out.println("@");
return new Symbol(sym.ARROBA,yyline,yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 11:
            { System.out.println("algo"); 
return new Symbol(sym.CARACTERES,yyline,yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 12:
            { System.out.println("["); 
return new Symbol(sym.CORCHETEIZ,yyline,yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 13:
            { System.out.println("]"); 
return new Symbol(sym.CORCHETEDE,yyline,yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 14:
            { System.out.println("<-"); 
return new Symbol(sym.IGUALDAD,yyline,yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 15:
            { System.out.println("algo entre comillas"); 
return new Symbol(sym.CHARCOMILLAS,yyline,yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 16:
            { System.out.println("arr");
return new Symbol(sym.ARR,yyline,yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 17:
            { System.out.println("div"); 
return new Symbol(sym.DIV,yyline,yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 18:
            { System.out.println("end"); 
return new Symbol(sym.END,yyline,yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 19:
            { System.out.println("Max"); 
return new Symbol(sym.MAX,yyline,yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 20:
            { System.out.println("Min"); 
return new Symbol(sym.MIN,yyline,yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 21:
            { System.out.println("mod"); 
return new Symbol(sym.MOD,yyline,yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 22:
            { System.out.println("mul"); 
return new Symbol(sym.MUL,yyline,yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 23:
            { System.out.println("res"); 
return new Symbol(sym.RES,yyline,yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 24:
            { System.out.println("sum"); 
return new Symbol(sym.SUM,yyline,yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 25:
            { System.out.println("var"); 
return new Symbol(sym.VAR,yyline,yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 26:
            { System.out.println("ejeX"); 
return new Symbol(sym.EJEX,yyline,yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 27:
            { System.out.println("ejeY"); 
return new Symbol(sym.EJEY,yyline,yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 28:
            { System.out.println("EXEC"); 
return new Symbol(sym.EXEC,yyline,yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 29:
            { System.out.println("Moda"); 
return new Symbol(sym.MODA,yyline,yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 30:
            { System.out.println("label"); 
return new Symbol(sym.LABEL,yyline,yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 31:
            { System.out.println("Media"); 
return new Symbol(sym.MEDIA,yyline,yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 32:
            { System.out.println("print"); 
return new Symbol(sym.PRINT,yyline,yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 33:
            { System.out.println("char[]"); 
return new Symbol(sym.CHAR,yyline,yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 34:
            { System.out.println("column"); 
return new Symbol(sym.COLUMN,yyline,yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 35:
            { System.out.println("double"); 
return new Symbol(sym.DOUBLE,yyline,yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 36:
            { System.out.println("titulo"); 
return new Symbol(sym.TITULO,yyline,yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 37:
            { System.out.println("values"); 
return new Symbol(sym.VALUES,yyline,yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 38:
            { System.out.println("console"); 
return new Symbol(sym.CONSOLE,yyline,yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 39:
            { System.out.println("Mediana"); 
return new Symbol(sym.MEDIANA,yyline,yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 40:
            { System.out.println("PROGRAM"); 
return new Symbol(sym.PROGRAM,yyline,yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 41:
            { System.out.println("tituloX"); 
return new Symbol(sym.TITULOX,yyline,yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 42:
            { System.out.println("tituloY"); 
return new Symbol(sym.TITULOY,yyline,yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 43:
            { System.out.println("graphPie"); 
return new Symbol(sym.GRAPHPIE,yyline,yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 44:
            { System.out.println("Varianza"); 
return new Symbol(sym.VARIANZA,yyline,yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 45:
            { System.out.println("graphLine"); 
return new Symbol(sym.GRAPHLINE,yyline,yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 46:
            { System.out.println("Histograma"); 
return new Symbol(sym.HISTOGRAMA,yyline,yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 47:
            { System.out.println("END PROGRAM"); 
return new Symbol(sym.ENDPROGRAM,yyline,yycolumn, yytext());
            }
          // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
