
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package test.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CARACTERUNICO = 18;
  public static final int DIFERENCIA = 9;
  public static final int DOSPUNTOS = 7;
  public static final int CARACTERES = 17;
  public static final int HASTA = 19;
  public static final int INTERSECCION = 11;
  public static final int OPERA = 4;
  public static final int IGUALDAD = 8;
  public static final int PARENTESISDE = 14;
  public static final int COMA = 15;
  public static final int LLAVEDE = 3;
  public static final int EOF = 0;
  public static final int CONJ = 5;
  public static final int UNION = 10;
  public static final int error = 1;
  public static final int PARENTESISIZ = 13;
  public static final int COMPLEMENTO = 12;
  public static final int LLAVEIZ = 2;
  public static final int PUNTOCOMA = 16;
  public static final int EVALUAR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVEIZ",
  "LLAVEDE",
  "OPERA",
  "CONJ",
  "EVALUAR",
  "DOSPUNTOS",
  "IGUALDAD",
  "DIFERENCIA",
  "UNION",
  "INTERSECCION",
  "COMPLEMENTO",
  "PARENTESISIZ",
  "PARENTESISDE",
  "COMA",
  "PUNTOCOMA",
  "CARACTERES",
  "CARACTERUNICO",
  "HASTA"
  };
}

